version: '2'
services:
  node-app:
    build: 
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    ports:
      - "2000:4000"
    command: npm run start