version: '2'
services:
  node-app:
    container_name: express-container
    env_file:
      - ./.env
    depends_on:
      - redis
  mongo:
    image: mongo
    restart: always
    volumes:
      - database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  redis: 
    image: redis
    depends_on:
      - mongo
  nginx: 
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
volumes:
  database: 
