version: '2'
services:
  node-app:
    build: 
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=developer
    ports:
      - "4000:4000"
    command: npm run start-dev